### ISSUE TITLE
forest() and other funcs documentation out of date

### ISSUE THREAD

**Issue by tommite** [gertvv/gemtc#39]
Documentation does not include use.description parameter

**Comment by gertvv** [comment]
forest() is an S3 generic, so the main documentation page for that is not under my control. The documentation for my version is under ?mtc.run, where it does have the use.description parameter. However there was a problem that made ?forest go to ?relative.effect if you chose the gemtc version, which I have now fixed.

What other docs are out of date?

**Comment by tommite** [comment]
Prob at least the function that I added the use.description, though that
might be S3 generic as well (plot). No way to override documentation of
those?

On Thu, Jun 2, 2016 at 9:52 AM, Gert van Valkenhoef <
notifications@github.com> wrote:

> forest() is an S3 generic, so the main documentation page for that is not
> under my control. The documentation for my version is under ?mtc.run, where
> it does have the use.description parameter. However there was a problem
> that made ?forest go to ?relative.effect if you chose the gemtc version,
> which I have now fixed.
>
> What other docs are out of date?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gertvv/gemtc/issues/39#issuecomment-223233298>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAFSvoo6xJNVK89slDnq9tQmOB-5KEXaks5qHpnegaJpZM4IsO-f>
> .
>



-- 
Dr Tommi Tervonen
tommi@smaa.fi
tel. +44 77 88 237 412

**Comment by gertvv** [comment]
I added the docs for that one already. You can provide your own docs, but they don't really override the existing one. If you ?forest with gemtc loaded you should get an option for whether you want the one from meta or from gemtc.
