### ISSUE TITLE
zero cell

### ISSUE THREAD

**Issue by PatriciaKZ** [gertvv/gemtc#49]
Dear all, 
Does gemtc allow to add 0.5 in the numerator of treatments with zero events? I can run it in OPENBUGS but when I try it in gemtc the model doesn´t run... the message says that there is a non-intenger for x. Thanks for any help

**Comment by gertvv** [comment]
This is not possible in JAGS. Such continuity corrections are generally not necessary in a Bayesian model, and that is considered one of the advantages of Bayesian methods. See for example https://doi.org/10.1002/sim.1761
