### ISSUE TITLE
Document how to get reproducible results

### ISSUE THREAD

**Issue by gertvv** [gertvv/gemtc#50]
_Originally posted by @mmkamso in https://github.com/gertvv/gemtc/issues/45#issuecomment-428729507_

**Comment by gertvv** [comment]
The seeds for the JAGS RNGs and the R RNG are independent, so both need to be set:

 - Use `set.seed()` prior to running `mtc.model()` to control the generation of random initial values.
 - Set `.RNG.name` and `.RNG.seed` in `model$inits` to control the JAGS RNGs.

**Comment by LittleStar84** [comment]
Hi Dr.Gert, can you show codes about how specify  .RNG.name and .RNG.seed in model$inits. Not familiar with Jags codes. thanks!
