### ISSUE TITLE
Prior precision

### ISSUE THREAD

**Issue by GustafRydevik** [gertvv/gemtc#52]
Hi, 

I have another question: The om.scale parameter is defined as " a very large change". In the code, this is then multiplied by 15, to generate a standard deviation of 15*veryLargeChange. What is the logic for the 15 times multiplier? A more appropriate vague prior in my mind would be the om.scale parameter itself. ...

**Comment by gertvv** [comment]
It's rather arbitrary, but was chosen to closely match previously published Bayesian NMAs at the time. See our paper http://dx.doi.org/10.1002/jrsm.1054 (preprint: http://drugis.org/files/network-auto.pdf).

I do agree it would be nice to be able to set the prior precision / variance / standard deviation explicitly, though.
