### ISSUE TITLE
How to specify reference treatment in mtc.anohe?

### ISSUE THREAD

**Issue by DivyeshThakker** [gertvv/gemtc#53]
Hi

for mtc.anohe, how can i specify reference treatment? because while plotting forest plot, i am able to specify reference treatment with the use of relative.effect(..., t1="Placebo") but not in the mtc.anohe and so it's giving output by taking different reference treatment. i would appreciate ur help.

**Comment by gertvv** [comment]
Closing, as not planning to implement this. I don't see why it's relevant.
