### ISSUE TITLE
Handling SMDs

### ISSUE THREAD

**Issue by coraschefft** [gertvv/gemtc#55]
Hey Gert,

I'm trying to run an analysis with 50 two arm studies and 8 three arm studies using SMDs.
I created the SMDs and respective std.errors by running the pairwise() function of the package meta, applying Hedges' g and then preparing the data for mtc.network. For baseline standard errors in three arm trials I entered the mean of all standard errors of pairwise comparisons of the multiarm trial.
--> is that correct at all? If not how do I estimate the baseline se?

When running mtc.model() I get the warning In sqrt(diag(sigma)) : NaNs produced. 
 --> how to deal with this warning? Apparently there are negative numbers in the diagonal of a var/cov Matrix.....

**Comment by gertvv** [comment]
The standard error specified for the reference arm must be smaller than any of the standard errors for the differences specified within the study.

**Comment by gertvv** [comment]
The standard error of the reference arm squared is the Covariance of each pair of treatment differences, that is
Var_{A,B} = Var_{A} + Var_{B}
Var_{A,C} = Var_{A} + Var_{C}
Quite often if Var_{A} is not known/given, it is imputed by assuming a correlation (usually between 0.3 and 0.7) - you should be able to find examples of this in the literature, e.g. by Salanti.

**Comment by coraschefft** [comment]
Thank you, just now saw your reply on this account. 
Best
Cora

Von meinem iPhone gesendet
