### ISSUE TITLE
GeMTC not available from CRAN

### ISSUE THREAD

**Issue by benskov** [gertvv/gemtc#56]
Dear Gert,

We really appreciate GeMTC, but it no longer seems available from CRAN; screen dump: 

![image](https://user-images.githubusercontent.com/24407836/84641852-f5146400-aefb-11ea-9fd7-874957c4dc4d.png)

Do you expect GeMTC to become available through CRAN again (i.e. is this is a transient problem), or is it the result of conscious decision?

Cheers,
Ben

**Comment by gertvv** [comment]
Dear Ben,

This is due to breaking changes in R. I do plan to make it available again, but wasn't able to action this at the notice given.

Best,

Gert

**Comment by gertvv** [comment]
Dear Ben,

I've fixed the issues and the package is with the CRAN maintainers for review. Thanks for reporting this!

Best,

Gert

**Comment by gertvv** [comment]
The package is now available on CRAN again.

**Comment by benskov** [comment]
Dear Gert, 

Thanks for the swift fix, and for a nice package!

Cheers,
Ben
