### ISSUE TITLE
Multiple measurements of the same construct within each arm

### ISSUE THREAD

**Issue by mnoetel** [gertvv/gemtc#60]
It's common in systematic reviews to find papers with multiple effect sizes reported for the same arm (e.g., two measures of depression). This is often managed by meta-analytic SEM (see metasem) or multilevel meta-analyses (see metafor). Could this be added for gemtc?

Maybe the MCMC could randomly sample from the effect sizes within the study?

**Comment by gertvv** [comment]
Hi @mnoetel - thanks for getting in touch. I'm aware of some BHMs for this type of use case, but don't have any plans to add this. The package is mostly in maintenance mode at the moment, at least until either I find someone to take over development or the package somehow becomes relevant again to my day job. I would also be happy to consider a pull request should anyone want to develop this but not take over as maintainer.
